title: Darrell Lokadeva Lim
#logo
description: Hi there, I'm Darrell Lokadeva Lim,  but you can call me Darrell. I am an Information Systems student at Sampoerna University-University of Arizona Joint Campus. I have a strong interest in data science, particularly on how data is leveraged to help companies in decision-making. I am very eager to apply my skills in data analysis and programming in real-world projects through internships! 


show_downloads: false
theme: jekyll-theme-minimal
